rag-function: "reciprocal_rank_fusion"
llm-query-template: |-
  Answer the following question based on this context:

  {context}

  Question: {question}
multi-query-request-template: |-
  You are a helpful assistant that generates multiple sub-questions related to an input question.
  The goal is to break down the input into a set of sub-problems / sub-questions that can be answers in isolation.
  Generate multiple search queries related to: {question}

  You must only generate 3 queries. No more than 3 is allowed.

  Example:
  The three queries are (3 queries):
  1. This is the first query.
  2. This is the second query.
  3. This is the third query.

  The three queries are (3 queries):